### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by philitell** [TheFe91/cached_firestorage#5]
Please support firebase_storage >12.0.0 and firebase_core >3.0.0

Thanks for your work on this package.

**Comment by TheFe91** [comment]
Hi @philitell 
I bumped the dependencies and the plugin is now supporting the latest versions of `firebase_storage` and `firebase_core` as per request.

Unfortunately at the moment I cannot publish on [pub.dev](https://pub.dev) because the `get_storage` dependency has not been updated since 16 months and has outdated packages too 😢 I had to fork that repo and update the dependencies myself, making `cached_firestorage` point to the new forked repo. However this violates the Pub rule for which no published package can point to a repo.

If you need to use the `cached_firestorage` package urgently I suggest you to directly point to this repo by doing in your `pubspec.yaml` file

```yaml
...
cached_firestorage:
  git: https://github.com/TheFe91/cached_firestorage
...
```

This will work for now, in the meanwhile I'll find out a solution

**Comment by philitell** [comment]
Thank you very much!!!
